// AddStudentModal — wired to backend with auto-generated admission number + temp password
'use client';

import React, { useState } from 'react';
import { X, CheckCircle, Copy, Check } from 'lucide-react';
import { createStudent } from '@/lib/api';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface AddStudentModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface StudentFormData {
  // Step 1: Student details
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  dateOfBirth: string;
  gender: string;
  country: string;
  city: string;
  state: string;
  // Step 2: Academic info (no studentId — auto-generated by backend)
  currentGrade: string;
  classSection: string;
  // Step 3: Guardian info
  guardianName: string;
  relationship: string;
  guardianPhone: string;
  guardianEmail: string;
  emergencyContact: string;
}

interface CreatedCredentials {
  admissionNumber: string;
  tempPassword: string;
  email: string;
  studentId: string;
}

const INITIAL_FORM: StudentFormData = {
  firstName: '',
  lastName: '',
  email: '',
  phoneNumber: '',
  dateOfBirth: '',
  gender: '',
  country: 'Nigeria',
  city: '',
  state: '',
  currentGrade: '',
  classSection: '',
  guardianName: '',
  relationship: '',
  guardianPhone: '',
  guardianEmail: '',
  emergencyContact: '',
};

const AddStudentModal: React.FC<AddStudentModalProps> = ({ isOpen, onClose }) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [showSuccess, setShowSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [credentials, setCredentials] = useState<CreatedCredentials | null>(null);
  const [copied, setCopied] = useState(false);
  const [formData, setFormData] = useState<StudentFormData>(INITIAL_FORM);

  const nigerianStates = [
    'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
    'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe', 'Imo',
    'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos',
    'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers',
    'Sokoto', 'Taraba', 'Yobe', 'Zamfara', 'FCT',
  ];

  const gradeLevels = [
    'Primary 1', 'Primary 2', 'Primary 3', 'Primary 4', 'Primary 5', 'Primary 6',
    'JSS 1', 'JSS 2', 'JSS 3', 'SS 1', 'SS 2', 'SS 3',
  ];

  const classSections = ['A', 'B', 'C', 'D', 'E'];
  const genders = ['Male', 'Female'];

  if (!isOpen) return null;

  const handleInputChange = (field: keyof StudentFormData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (error) setError('');
  };

  const isStepValid = (step: number): boolean => {
    switch (step) {
      case 1:
        return !!(
          formData.firstName &&
          formData.lastName &&
          formData.email &&
          formData.gender
        );
      case 2:
        return !!(formData.currentGrade && formData.classSection);
      case 3:
        return !!(
          formData.guardianName &&
          formData.relationship &&
          formData.guardianPhone
        );
      default:
        return false;
    }
  };

  const handleNext = () => {
    if (currentStep < 3) setCurrentStep(currentStep + 1);
  };

  const handleBack = () => {
    if (currentStep > 1) setCurrentStep(currentStep - 1);
  };

  const handleSubmit = async () => {
    setLoading(true);
    setError('');

    try {
      const className = formData.classSection
        ? `${formData.currentGrade} ${formData.classSection}`
        : formData.currentGrade;

      // Send the full payload — the backend persists every demographic /
      // guardian field that's provided. Empty strings are stripped here so we
      // don't write blank values into the DB just because the user skipped a
      // step.
      const cleaned = <T extends Record<string, string>>(obj: T) =>
        Object.fromEntries(
          Object.entries(obj).filter(([, v]) => v !== '' && v !== undefined)
        );

      const result = await createStudent({
        email: formData.email,
        firstName: formData.firstName,
        lastName: formData.lastName,
        className,
        ...cleaned({
          phoneNumber: formData.phoneNumber,
          dateOfBirth: formData.dateOfBirth,
          gender: formData.gender,
          city: formData.city,
          state: formData.state,
          country: formData.country,
          guardianName: formData.guardianName,
          relationship: formData.relationship,
          guardianPhone: formData.guardianPhone,
          guardianEmail: formData.guardianEmail,
          emergencyContact: formData.emergencyContact,
        }),
      });

      if (result.success && result.data) {
        setCredentials({
          admissionNumber: result.data.admissionNumber,
          tempPassword: result.data.tempPassword,
          email: result.data.email,
          studentId: result.data.id,
        });
        setShowSuccess(true);
      } else {
        setError(result.message || 'Failed to create student');
      }
    } catch (err: any) {
      if (err.status === 400) {
        setError(err.message || 'Invalid student data. Please check the form.');
      } else if (err.status === 409 || err.message?.includes('already exists')) {
        setError('A student with this email already exists.');
      } else if (err.isNetworkError) {
        setError('Unable to reach the server. Check your connection.');
      } else {
        setError(err.message || 'Something went wrong. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleCopyCredentials = async () => {
    if (!credentials) return;
    const text = `TREMAD Schools — Student Login Credentials\n\nAdmission Number: ${credentials.admissionNumber}\nTemporary Password: ${credentials.tempPassword}\nEmail: ${credentials.email}\n\nPlease log in and change your password immediately.`;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleClose = () => {
    setCurrentStep(1);
    setShowSuccess(false);
    setError('');
    setCredentials(null);
    setCopied(false);
    setFormData(INITIAL_FORM);
    onClose();
  };

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget && !loading) handleClose();
  };

  const totalSteps = 3;

  return (
    <div
      onClick={handleBackdropClick}
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-2 sm:p-4 md:p-6 overflow-y-auto"
    >
      {!showSuccess ? (
        <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[95vh] overflow-y-auto my-auto">
          {/* Header */}
          <div className="border-b border-gray-200 p-4 sm:p-6">
            <div className="flex items-center justify-between mb-3 sm:mb-4">
              <h2 className="text-lg sm:text-xl font-semibold text-gray-900">
                Add new student
              </h2>
              <button
                onClick={handleClose}
                disabled={loading}
                className="text-gray-400 hover:text-gray-600 transition-colors min-w-[44px] min-h-[44px] flex items-center justify-center -mr-2"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Stepper */}
            <div className="flex items-center gap-2 sm:gap-4 text-xs sm:text-sm">
              {['Student details', 'Academic info', 'Guardian info'].map((label, i) => (
                <div key={i} className="flex-1">
                  <div className={`text-center mb-1 sm:mb-2 ${currentStep === i + 1 ? 'text-green-600 font-medium' : currentStep > i + 1 ? 'text-green-600' : 'text-gray-400'}`}>
                    {label}
                  </div>
                  <div className={`h-1 rounded-full ${currentStep > i ? 'bg-green-600' : 'bg-gray-200'}`} />
                </div>
              ))}
            </div>
          </div>

          {/* Error */}
          {error && (
            <div className="mx-4 sm:mx-6 mt-4 p-3 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-sm text-red-600">{error}</p>
            </div>
          )}

          {/* Form Body */}
          <div className="p-4 sm:p-6">
            {/* Step 1: Student details */}
            {currentStep === 1 && (
              <div className="space-y-3 sm:space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">First name *</label>
                    <input
                      type="text"
                      value={formData.firstName}
                      onChange={(e) => handleInputChange('firstName', e.target.value)}
                      placeholder="Enter first name"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Last name *</label>
                    <input
                      type="text"
                      value={formData.lastName}
                      onChange={(e) => handleInputChange('lastName', e.target.value)}
                      placeholder="Enter last name"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Email *</label>
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => handleInputChange('email', e.target.value)}
                    placeholder="Enter email address"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Phone number</label>
                    <input
                      type="tel"
                      value={formData.phoneNumber}
                      onChange={(e) => handleInputChange('phoneNumber', e.target.value)}
                      placeholder="Enter phone number"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Date of birth</label>
                    <input
                      type="date"
                      value={formData.dateOfBirth}
                      onChange={(e) => handleInputChange('dateOfBirth', e.target.value)}
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Gender *</label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                        <span className={formData.gender ? 'text-gray-900' : 'text-gray-400'}>
                          {formData.gender || 'Select gender'}
                        </span>
                        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent>
                      {genders.map((g) => (
                        <DropdownMenuItem key={g} onClick={() => handleInputChange('gender', g.toLowerCase())}>
                          {g}
                        </DropdownMenuItem>
                      ))}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">City</label>
                    <input
                      type="text"
                      value={formData.city}
                      onChange={(e) => handleInputChange('city', e.target.value)}
                      placeholder="Enter city"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">State</label>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                          <span className={formData.state ? 'text-gray-900' : 'text-gray-400'}>
                            {formData.state || 'Select state'}
                          </span>
                          <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent className="max-h-60 overflow-y-auto">
                        {nigerianStates.map((s) => (
                          <DropdownMenuItem key={s} onClick={() => handleInputChange('state', s)}>
                            {s}
                          </DropdownMenuItem>
                        ))}
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
              </div>
            )}

            {/* Step 2: Academic info — NO student ID field, it's auto-generated */}
            {currentStep === 2 && (
              <div className="space-y-3 sm:space-y-4">
                <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
                  <p className="text-sm text-green-700">
                    The student&apos;s admission number and temporary password will be auto-generated when you submit.
                  </p>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Current grade *</label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                        <span className={formData.currentGrade ? 'text-gray-900' : 'text-gray-400'}>
                          {formData.currentGrade || 'Select grade'}
                        </span>
                        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent className="max-h-60 overflow-y-auto">
                      {gradeLevels.map((grade) => (
                        <DropdownMenuItem key={grade} onClick={() => handleInputChange('currentGrade', grade)}>
                          {grade}
                        </DropdownMenuItem>
                      ))}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Class section *</label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                        <span className={formData.classSection ? 'text-gray-900' : 'text-gray-400'}>
                          {formData.classSection ? `${formData.currentGrade} ${formData.classSection}` : 'Select section'}
                        </span>
                        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent>
                      {classSections.map((section) => (
                        <DropdownMenuItem key={section} onClick={() => handleInputChange('classSection', section)}>
                          {formData.currentGrade} {section}
                        </DropdownMenuItem>
                      ))}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </div>
            )}

            {/* Step 3: Guardian info */}
            {currentStep === 3 && (
              <div className="space-y-3 sm:space-y-4">
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Guardian name *</label>
                  <input
                    type="text"
                    value={formData.guardianName}
                    onChange={(e) => handleInputChange('guardianName', e.target.value)}
                    placeholder="Enter full name"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Relationship *</label>
                  <input
                    type="text"
                    value={formData.relationship}
                    onChange={(e) => handleInputChange('relationship', e.target.value)}
                    placeholder="e.g. Father, Mother, Guardian"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Guardian phone *</label>
                    <input
                      type="tel"
                      value={formData.guardianPhone}
                      onChange={(e) => handleInputChange('guardianPhone', e.target.value)}
                      placeholder="Enter phone number"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Guardian email</label>
                    <input
                      type="email"
                      value={formData.guardianEmail}
                      onChange={(e) => handleInputChange('guardianEmail', e.target.value)}
                      placeholder="Enter email"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Emergency contact</label>
                  <input
                    type="tel"
                    value={formData.emergencyContact}
                    onChange={(e) => handleInputChange('emergencyContact', e.target.value)}
                    placeholder="Enter phone number"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="border-t border-gray-200 px-4 sm:px-6 py-3 sm:py-4">
            <div className="flex justify-between items-center">
              <button
                onClick={handleBack}
                disabled={loading}
                className={`px-3 sm:px-4 py-2.5 text-xs sm:text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors min-h-[44px] ${
                  currentStep === 1 ? 'invisible' : ''
                }`}
              >
                Back
              </button>

              <div className="flex gap-2 sm:gap-3">
                {currentStep < 3 ? (
                  <button
                    onClick={handleNext}
                    disabled={!isStepValid(currentStep)}
                    className={`px-4 sm:px-6 py-2.5 text-xs sm:text-sm font-medium rounded-lg transition-all min-h-[44px] ${
                      isStepValid(currentStep)
                        ? 'text-white bg-green-600 hover:bg-green-700'
                        : 'text-gray-400 bg-gray-200 cursor-not-allowed'
                    }`}
                  >
                    Continue
                  </button>
                ) : (
                  <button
                    onClick={handleSubmit}
                    disabled={!isStepValid(currentStep) || loading}
                    className={`px-4 sm:px-6 py-2.5 text-xs sm:text-sm font-medium rounded-lg transition-all min-h-[44px] flex items-center gap-2 ${
                      isStepValid(currentStep) && !loading
                        ? 'text-white bg-green-600 hover:bg-green-700'
                        : 'text-gray-400 bg-gray-200 cursor-not-allowed'
                    }`}
                  >
                    {loading && (
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    )}
                    {loading ? 'Creating...' : 'Submit'}
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* Success Screen — shows generated credentials */
        <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6 sm:p-8 mx-2">
          <div className="text-center mb-6">
            <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-full bg-green-100 flex items-center justify-center mx-auto mb-3">
              <CheckCircle className="w-7 h-7 sm:w-8 sm:h-8 text-green-600" />
            </div>
            <h2 className="text-lg sm:text-xl font-semibold text-gray-900 mb-1">Student Created!</h2>
            <p className="text-sm text-gray-500">Share these credentials with the student</p>
          </div>

          {credentials && (
            <div className="bg-gray-50 rounded-lg p-4 mb-6 space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-xs text-gray-500 uppercase tracking-wide">Admission Number</span>
                <span className="text-sm font-mono font-semibold text-gray-900">{credentials.admissionNumber}</span>
              </div>
              <div className="border-t border-gray-200" />
              <div className="flex justify-between items-center">
                <span className="text-xs text-gray-500 uppercase tracking-wide">Temporary Password</span>
                <span className="text-sm font-mono font-semibold text-gray-900">{credentials.tempPassword}</span>
              </div>
              <div className="border-t border-gray-200" />
              <div className="flex justify-between items-center">
                <span className="text-xs text-gray-500 uppercase tracking-wide">Email</span>
                <span className="text-sm text-gray-900">{credentials.email}</span>
              </div>
            </div>
          )}

          <div className="flex gap-3">
            <button
              onClick={handleCopyCredentials}
              className="flex-1 px-4 py-2.5 text-sm font-medium text-green-700 bg-green-50 hover:bg-green-100 rounded-lg transition-colors flex items-center justify-center gap-2 min-h-[44px]"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy Credentials
                </>
              )}
            </button>
            <button
              onClick={handleClose}
              className="flex-1 px-4 py-2.5 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors min-h-[44px]"
            >
              Close
            </button>
          </div>

          <p className="text-xs text-gray-400 text-center mt-4">
            The student will be prompted to change their password on first login.
          </p>
        </div>
      )}
    </div>
  );
};

export default AddStudentModal;
