// AddStudentModal — wired to backend with auto-generated admission number + temp password
'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { X, CheckCircle, Copy, Check } from 'lucide-react';
import { createStudent, uploadUserAvatar } from '@/lib/api';
import AvatarPicker from '@/components/shared/AvatarPicker';
import { getApiErrorMessage } from '@/lib/api/client';
import WizardProgress from '@/components/shared/WizardProgress';
import { GRADE_LEVELS, CLASS_SECTIONS } from '@/Constants/classes';
import {
  getCurriculum,
  type Requirement,
  type Subject,
} from '@/lib/api/curriculum.service';
import { NIGERIAN_STATES, getLGAsForState } from '@/Constants/NigeriaStates';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';



interface StudentFormData {
  /** Government-issued Learner's Identification Number (optional). */
  lin: string;
  // Step 1: Student details
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  dateOfBirth: string;
  gender: string;
  country: string;
  city: string;
  state: string;
  // Step 2: Academic info (no studentId — auto-generated by backend)
  currentGrade: string;
  classSection: string;
  // Step 3: Guardian info
  guardianName: string;
  relationship: string;
  guardianPhone: string;
  guardianEmail: string;
  emergencyContact: string;
}

interface CreatedCredentials {
  admissionNumber: string;
  tempPassword: string;
  email: string;
  studentId: string;
}

const INITIAL_FORM: StudentFormData = {
  firstName: '',
  lastName: '',
  email: '',
  phoneNumber: '',
  dateOfBirth: '',
  gender: '',
  country: 'Nigeria',
  city: '',
  state: '',
  currentGrade: '',
  classSection: '',
  lin: '',
  guardianName: '',
  relationship: '',
  guardianPhone: '',
  guardianEmail: '',
  emergencyContact: '',
};

interface AddStudentModalProps {
  isOpen: boolean;
  onClose: () => void;
}

/** A field counts as done once it holds something other than whitespace. */
const filled = (v: string) => Boolean(v && v.trim());

/**
 * What each step requires, in order.
 *
 * SINGLE SOURCE for two things that must agree: how full the progress bar is,
 * and whether "Continue" is enabled. They were separate before — the bar was
 * a fixed three-state thing and validity was a switch statement — which is
 * exactly the arrangement where one gets a new field and the other doesn't.
 *
 * Step 3 requires nothing: subjects come prefilled from the class curriculum
 * and a class with none is legitimate, so it reads as complete on arrival.
 */
const STEP_CHECKS: Array<Array<(f: StudentFormData) => boolean>> = [
  [
    (f) => filled(f.firstName),
    (f) => filled(f.lastName),
    (f) => filled(f.email),
    (f) => filled(f.gender),
  ],
  [(f) => filled(f.currentGrade), (f) => filled(f.classSection)],
  [],
  [
    (f) => filled(f.guardianName),
    (f) => filled(f.relationship),
    (f) => filled(f.guardianPhone),
  ],
];

const STEP_LABELS = [
  'Student details',
  'Academic info',
  'Subjects & activities',
  'Guardian info',
];

/** 0–1 for one step. A step with nothing required is complete by definition. */
const stepRatio = (step: number, form: StudentFormData): number => {
  const checks = STEP_CHECKS[step - 1] ?? [];
  if (!checks.length) return 1;
  return checks.filter((c) => c(form)).length / checks.length;
};

const AddStudentModal: React.FC<AddStudentModalProps> = ({ isOpen, onClose }) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [showSuccess, setShowSuccess] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [credentials, setCredentials] = useState<CreatedCredentials | null>(null);
  const [copied, setCopied] = useState(false);
  const [formData, setFormData] = useState<StudentFormData>(INITIAL_FORM);
  // Held until the student exists — the photo is keyed by user id on
  // Cloudinary, so there's nothing to attach it to before creation.
  const [photo, setPhoto] = useState<File | null>(null);
  const [photoWarning, setPhotoWarning] = useState('');

  // ---- What this student will take -------------------------------------
  // Read from the chosen grade's curriculum, then owned by this student. The
  // curriculum is a template: unticking here changes this student only, and a
  // later edit to the class's curriculum never reaches back into them.
  const [curriculumSubjects, setCurriculumSubjects] = useState<
    Array<{ subject: Subject; requirement: Requirement }>
  >([]);
  const [curriculumActivities, setCurriculumActivities] = useState<Subject[]>([]);
  const [chosenSubjects, setChosenSubjects] = useState<Set<string>>(new Set());
  const [chosenActivities, setChosenActivities] = useState<Set<string>>(new Set());
  const [loadingCurriculum, setLoadingCurriculum] = useState(false);
  const [curriculumError, setCurriculumError] = useState('');

  const grade = formData.currentGrade;

  const loadCurriculum = useCallback(async () => {
    if (!grade) {
      setCurriculumSubjects([]);
      setCurriculumActivities([]);
      setChosenSubjects(new Set());
      setChosenActivities(new Set());
      return;
    }
    setLoadingCurriculum(true);
    setCurriculumError('');
    try {
      const res = await getCurriculum(grade);
      if (res?.success && res.data) {
        const subs = (res.data.curriculum.subjects || [])
          .map((e) => ({
            subject: typeof e.subject === 'string' ? null : e.subject,
            requirement: e.requirement,
          }))
          // A subject archived since the curriculum was saved comes back
          // unpopulated; drop it rather than render a nameless row.
          .filter((e): e is { subject: Subject; requirement: Requirement } =>
            Boolean(e.subject)
          );
        const acts = (res.data.curriculum.activities || [])
          .map((a) => (typeof a === 'string' ? null : a))
          .filter((a): a is Subject => Boolean(a));

        setCurriculumSubjects(subs);
        setCurriculumActivities(acts);
        // Everything starts ticked — the admin unticks what this student won't
        // take, rather than rebuilding the class's list by hand each time.
        setChosenSubjects(new Set(subs.map((e) => e.subject._id)));
        setChosenActivities(new Set(acts.map((a) => a._id)));
      } else {
        setCurriculumError(res?.message || 'Could not load this class.');
      }
    } catch {
      setCurriculumError('Could not load this class.');
    } finally {
      setLoadingCurriculum(false);
    }
  }, [grade]);

  // Re-reads whenever the grade changes, including back to blank. Keyed on the
  // GRADE alone: a curriculum belongs to "Basic 1" — not to a section, and no
  // longer to a session either.
  //
  // Guarded on `isOpen` so a closed modal isn't fetching in the background,
  // but the hook itself still RUNS on every render — see the note on the
  // early return below.
  useEffect(() => {
    if (!isOpen) return;
    loadCurriculum();
  }, [isOpen, loadCurriculum]);

  const coreIds = useMemo(
    () =>
      new Set(
        curriculumSubjects
          .filter((e) => e.requirement === 'core')
          .map((e) => e.subject._id)
      ),
    [curriculumSubjects]
  );

  // EVERY hook must appear above this line. React identifies hooks by call
  // order, so a `useState`/`useEffect`/`useMemo` placed after an early return
  // is skipped on the renders that bail out — and the next full render reads
  // another hook's state. It works right up until the modal is closed once.
  if (!isOpen) return null;

  // Full 36 states + FCT, sourced from the shared NigeriaStates dataset.
  const nigerianStates = NIGERIAN_STATES;
  // LGAs for whichever state is currently selected (empty until one is picked).
  const availableLGAs = getLGAsForState(formData.state);

  // Shared with the Timetable builder so a grade here always matches a grade
  // there — see Constants/classes.ts.
  const gradeLevels = GRADE_LEVELS;
  const classSections = CLASS_SECTIONS;
  const genders = ['Male', 'Female'];

  const handleInputChange = (field: keyof StudentFormData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (error) setError('');
  };

  // Selecting a state also clears the Local Government (`city`) — an LGA from a
  // previously-chosen state would be meaningless under the new one.
  const handleStateChange = (state: string) => {
    setFormData((prev) => ({ ...prev, state, city: '' }));
    if (error) setError('');
  };

  // Same checks the progress bar counts, so a full segment and an enabled
  // Continue button can never disagree.
  const isStepValid = (step: number): boolean =>
    stepRatio(step, formData) === 1;

  const handleNext = () => {
    if (currentStep < totalSteps) setCurrentStep(currentStep + 1);
  };

  const handleBack = () => {
    if (currentStep > 1) setCurrentStep(currentStep - 1);
  };

  const handleSubmit = async () => {
    setLoading(true);
    setError('');

    try {
      const className = formData.classSection
        ? `${formData.currentGrade} ${formData.classSection}`
        : formData.currentGrade;

      // Send the full payload — the backend persists every demographic /
      // guardian field that's provided. Empty strings are stripped here so we
      // don't write blank values into the DB just because the user skipped a
      // step.
      const cleaned = <T extends Record<string, string>>(obj: T) =>
        Object.fromEntries(
          Object.entries(obj).filter(([, v]) => v !== '' && v !== undefined)
        );

      const result = await createStudent({
        email: formData.email,
        firstName: formData.firstName,
        lastName: formData.lastName,
        className,
        ...cleaned({
          lin: formData.lin,
          phoneNumber: formData.phoneNumber,
          dateOfBirth: formData.dateOfBirth,
          gender: formData.gender,
          city: formData.city,
          state: formData.state,
          country: formData.country,
          guardianName: formData.guardianName,
          relationship: formData.relationship,
          guardianPhone: formData.guardianPhone,
          guardianEmail: formData.guardianEmail,
          emergencyContact: formData.emergencyContact,
        }),
        // Snapshot. Sent as ids; the backend re-checks kind and de-duplicates.
        enrolledSubjects: curriculumSubjects
          .filter((e) => chosenSubjects.has(e.subject._id))
          .map((e) => ({ subject: e.subject._id, requirement: e.requirement })),
        enrolledActivities: [...chosenActivities],
      });

      if (result.success && result.data) {
        // The account exists now. A failed photo upload must NOT read as a
        // failed creation — surface it as a warning on the success screen and
        // let the admin retry from the student's detail page.
        if (photo && result.data.id) {
          try {
            const up = await uploadUserAvatar(result.data.id, photo);
            if (!up?.success) {
              setPhotoWarning(
                up?.message || 'The student was created, but the photo didn’t upload.'
              );
            }
          } catch (err: any) {
            setPhotoWarning(
              err?.status === 503
                ? 'The student was created, but photo uploads aren’t configured on the server.'
                : 'The student was created, but the photo didn’t upload. You can add it from their profile.'
            );
          }
        }

        setCredentials({
          admissionNumber: result.data.admissionNumber,
          tempPassword: result.data.tempPassword,
          email: result.data.email,
          studentId: result.data.id,
        });
        setShowSuccess(true);
      } else {
        setError(result.message || 'Failed to create student');
      }
    } catch (err: any) {
      if (err.status === 400) {
        // Validation failures carry the detail in `errors`, not `message`.
        setError(getApiErrorMessage(err, 'Invalid student data. Please check the form.'));
      } else if (err.status === 409 || err.message?.includes('already exists')) {
        setError('A student with this email already exists.');
      } else if (err.isNetworkError) {
        setError('Unable to reach the server. Check your connection.');
      } else {
        setError(err.message || 'Something went wrong. Please try again.');
      }
    } finally {
      setLoading(false);
    }
  };

  const handleCopyCredentials = async () => {
    if (!credentials) return;
    const text = `TREMAD Schools — Student Login Credentials\n\nAdmission Number: ${credentials.admissionNumber}\nTemporary Password: ${credentials.tempPassword}\nEmail: ${credentials.email}\n\nPlease log in and change your password immediately.`;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  /** Leaves the page. State is per-mount, so nothing needs resetting. */
  const handleClose = () => {
    setCurrentStep(1);
    setShowSuccess(false);
    setError('');
    setCredentials(null);
    setCopied(false);
    setFormData(INITIAL_FORM);
    setPhoto(null);
    setPhotoWarning('');
    // The curriculum picks belong to the student being created, so they reset
    // with everything else — reopening for the next student must not inherit
    // the last one's subjects.
    setChosenSubjects(new Set());
    setChosenActivities(new Set());
    onClose();
  };

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget && !loading) handleClose();
  };

  const totalSteps = 4;

  return (
    <div
      onClick={handleBackdropClick}
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-2 sm:p-4 md:p-6 overflow-y-auto"
    >
      {!showSuccess ? (
        <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[95vh] overflow-y-auto my-auto">
          {/* Header */}
          <div className="border-b border-gray-200 p-4 sm:p-6">
            <div className="flex items-center justify-between mb-3 sm:mb-4">
              <h2 className="text-lg sm:text-xl font-semibold text-gray-900">
                Add new student
              </h2>
              <button
                onClick={handleClose}
                disabled={loading}
                className="text-gray-400 hover:text-gray-600 transition-colors min-w-[44px] min-h-[44px] flex items-center justify-center -mr-2"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Fills as fields are completed — see WizardProgress. */}
            <WizardProgress
              steps={STEP_LABELS.map((label, i) => ({
                label,
                ratio: stepRatio(i + 1, formData),
              }))}
              current={currentStep}
              labelPosition="above"
              onStepClick={setCurrentStep}
            />
          </div>

          {/* Error */}
          {error && (
            <div className="mx-4 sm:mx-6 mt-4 p-3 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-sm text-red-600">{error}</p>
            </div>
          )}

          {/* Form Body */}
          <div className="p-4 sm:p-6">
            {/* Step 1: Student details */}
            {currentStep === 1 && (
              <div className="space-y-3 sm:space-y-4">
                <AvatarPicker
                  file={photo}
                  onChange={setPhoto}
                  uploading={loading && !!photo}
                  disabled={loading}
                />

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">First name *</label>
                    <input
                      type="text"
                      value={formData.firstName}
                      onChange={(e) => handleInputChange('firstName', e.target.value)}
                      placeholder="Enter first name"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Last name *</label>
                    <input
                      type="text"
                      value={formData.lastName}
                      onChange={(e) => handleInputChange('lastName', e.target.value)}
                      placeholder="Enter last name"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Email *</label>
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => handleInputChange('email', e.target.value)}
                    placeholder="Enter email address"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">
                    LIN <span className="text-gray-400 font-normal">(optional)</span>
                  </label>
                  <input
                    type="text"
                    value={formData.lin}
                    onChange={(e) => handleInputChange('lin', e.target.value.toUpperCase())}
                    placeholder="Learner's Identification Number"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                  <p className="text-xs text-gray-400 mt-1">
                    Issued by government — leave blank if the school hasn&apos;t received it yet.
                    It can be added later from the student&apos;s record.
                  </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Phone number</label>
                    <input
                      type="tel"
                      value={formData.phoneNumber}
                      onChange={(e) => handleInputChange('phoneNumber', e.target.value)}
                      placeholder="Enter phone number"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Date of birth</label>
                    <input
                      type="date"
                      value={formData.dateOfBirth}
                      onChange={(e) => handleInputChange('dateOfBirth', e.target.value)}
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Gender *</label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                        <span className={formData.gender ? 'text-gray-900' : 'text-gray-400'}>
                          {formData.gender || 'Select gender'}
                        </span>
                        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent>
                      {genders.map((g) => (
                        <DropdownMenuItem key={g} onClick={() => handleInputChange('gender', g.toLowerCase())}>
                          {g}
                        </DropdownMenuItem>
                      ))}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  {/* State Of Origin — drives the Local Government dropdown below */}
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">State Of Origin</label>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                          <span className={formData.state ? 'text-gray-900' : 'text-gray-400'}>
                            {formData.state || 'Select state of origin'}
                          </span>
                          <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent className="max-h-60 overflow-y-auto">
                        {nigerianStates.map((s) => (
                          <DropdownMenuItem key={s} onClick={() => handleStateChange(s)}>
                            {s}
                          </DropdownMenuItem>
                        ))}
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>

                  {/* Local Government — depends on the selected state. Disabled
                      until a state is chosen; its options come from that state's
                      LGA list. */}
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Local Government</label>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild disabled={!formData.state}>
                        <button
                          disabled={!formData.state}
                          className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px] disabled:bg-gray-50 disabled:cursor-not-allowed"
                        >
                          <span className={formData.city ? 'text-gray-900' : 'text-gray-400'}>
                            {formData.city || (formData.state ? 'Select local government' : 'Select a state first')}
                          </span>
                          <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent className="max-h-60 overflow-y-auto">
                        {availableLGAs.map((lga) => (
                          <DropdownMenuItem key={lga} onClick={() => handleInputChange('city', lga)}>
                            {lga}
                          </DropdownMenuItem>
                        ))}
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
              </div>
            )}

            {/* Step 2: Academic info — NO student ID field, it's auto-generated */}
            {currentStep === 2 && (
              <div className="space-y-3 sm:space-y-4">
                <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
                  <p className="text-sm text-green-700">
                    The student&apos;s admission number and temporary password will be auto-generated when you submit.
                  </p>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Current grade *</label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                        <span className={formData.currentGrade ? 'text-gray-900' : 'text-gray-400'}>
                          {formData.currentGrade || 'Select grade'}
                        </span>
                        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent className="max-h-60 overflow-y-auto">
                      {gradeLevels.map((grade) => (
                        <DropdownMenuItem key={grade} onClick={() => handleInputChange('currentGrade', grade)}>
                          {grade}
                        </DropdownMenuItem>
                      ))}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Class section *</label>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <button className="w-full px-3 py-2.5 text-sm text-left border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent flex justify-between items-center min-h-[44px]">
                        <span className={formData.classSection ? 'text-gray-900' : 'text-gray-400'}>
                          {formData.classSection ? `${formData.currentGrade} ${formData.classSection}` : 'Select section'}
                        </span>
                        <svg className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                        </svg>
                      </button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent>
                      {classSections.map((section) => (
                        <DropdownMenuItem key={section} onClick={() => handleInputChange('classSection', section)}>
                          {formData.currentGrade} {section}
                        </DropdownMenuItem>
                      ))}
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </div>
            )}

            {/* Step 3: Subjects & activities, prefilled from the class */}
            {currentStep === 3 && (
              <div className="space-y-4">
                {!grade ? (
                  <p className="text-sm text-gray-500">
                    Go back and choose a grade first.
                  </p>
                ) : loadingCurriculum ? (
                  <p className="text-sm text-gray-500">
                    Loading what {grade} takes&hellip;
                  </p>
                ) : curriculumError ? (
                  <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
                    <p className="text-sm text-red-600">{curriculumError}</p>
                  </div>
                ) : curriculumSubjects.length === 0 &&
                  curriculumActivities.length === 0 ? (
                  <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg">
                    <p className="text-sm text-amber-800">
                      Nothing has been assigned to {grade} yet. You can still
                      create this student &mdash; set the class up under
                      Timetable &rarr; Curriculum and edit them afterwards.
                    </p>
                  </div>
                ) : (
                  <>
                    <p className="text-xs text-gray-500">
                      Everything assigned to {grade} is ticked. Untick anything
                      this student won&apos;t take. Core subjects can&apos;t be
                      removed.
                    </p>

                    {curriculumSubjects.length > 0 && (
                      <PickList
                        title="Subjects"
                        rows={curriculumSubjects.map((e) => ({
                          id: e.subject._id,
                          name: e.subject.name,
                          colour: e.subject.colour,
                          locked: e.requirement === 'core',
                          badge: e.requirement,
                        }))}
                        chosen={chosenSubjects}
                        onToggle={(id) => {
                          // Core subjects are fixed by the curriculum — the
                          // lock is the whole point of the core/elective split.
                          if (coreIds.has(id)) return;
                          setChosenSubjects((prev) => {
                            const next = new Set(prev);
                            if (next.has(id)) next.delete(id);
                            else next.add(id);
                            return next;
                          });
                        }}
                      />
                    )}

                    {curriculumActivities.length > 0 && (
                      <PickList
                        title="Activities"
                        rows={curriculumActivities.map((a) => ({
                          id: a._id,
                          name: a.name,
                          colour: a.colour,
                          locked: false,
                        }))}
                        chosen={chosenActivities}
                        onToggle={(id) =>
                          setChosenActivities((prev) => {
                            const next = new Set(prev);
                            if (next.has(id)) next.delete(id);
                            else next.add(id);
                            return next;
                          })
                        }
                      />
                    )}
                  </>
                )}
              </div>
            )}

            {/* Step 4: Guardian info */}
            {currentStep === 4 && (
              <div className="space-y-3 sm:space-y-4">
                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Guardian name *</label>
                  <input
                    type="text"
                    value={formData.guardianName}
                    onChange={(e) => handleInputChange('guardianName', e.target.value)}
                    placeholder="Enter full name"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Relationship *</label>
                  <input
                    type="text"
                    value={formData.relationship}
                    onChange={(e) => handleInputChange('relationship', e.target.value)}
                    placeholder="e.g. Father, Mother, Guardian"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Guardian phone *</label>
                    <input
                      type="tel"
                      value={formData.guardianPhone}
                      onChange={(e) => handleInputChange('guardianPhone', e.target.value)}
                      placeholder="Enter phone number"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                  <div>
                    <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Guardian email</label>
                    <input
                      type="email"
                      value={formData.guardianEmail}
                      onChange={(e) => handleInputChange('guardianEmail', e.target.value)}
                      placeholder="Enter email"
                      className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs sm:text-sm font-medium text-gray-700 mb-1">Emergency contact</label>
                  <input
                    type="tel"
                    value={formData.emergencyContact}
                    onChange={(e) => handleInputChange('emergencyContact', e.target.value)}
                    placeholder="Enter phone number"
                    className="w-full px-3 py-2.5 text-sm border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-transparent min-h-[44px]"
                  />
                </div>
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="border-t border-gray-200 px-4 sm:px-6 py-3 sm:py-4">
            <div className="flex justify-between items-center">
              <button
                onClick={handleBack}
                disabled={loading}
                className={`px-3 sm:px-4 py-2.5 text-xs sm:text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors min-h-[44px] ${
                  currentStep === 1 ? 'invisible' : ''
                }`}
              >
                Back
              </button>

              <div className="flex gap-2 sm:gap-3">
                {currentStep < totalSteps ? (
                  <button
                    onClick={handleNext}
                    disabled={!isStepValid(currentStep)}
                    className={`px-4 sm:px-6 py-2.5 text-xs sm:text-sm font-medium rounded-lg transition-all min-h-[44px] ${
                      isStepValid(currentStep)
                        ? 'text-white bg-green-600 hover:bg-green-700'
                        : 'text-gray-400 bg-gray-200 cursor-not-allowed'
                    }`}
                  >
                    Continue
                  </button>
                ) : (
                  <button
                    onClick={handleSubmit}
                    disabled={!isStepValid(currentStep) || loading}
                    className={`px-4 sm:px-6 py-2.5 text-xs sm:text-sm font-medium rounded-lg transition-all min-h-[44px] flex items-center gap-2 ${
                      isStepValid(currentStep) && !loading
                        ? 'text-white bg-green-600 hover:bg-green-700'
                        : 'text-gray-400 bg-gray-200 cursor-not-allowed'
                    }`}
                  >
                    {loading && (
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    )}
                    {loading ? 'Creating...' : 'Submit'}
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* Success Screen — shows generated credentials */
        <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6 sm:p-8 mx-2">
          <div className="text-center mb-6">
            <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-full bg-green-100 flex items-center justify-center mx-auto mb-3">
              <CheckCircle className="w-7 h-7 sm:w-8 sm:h-8 text-green-600" />
            </div>
            <h2 className="text-lg sm:text-xl font-semibold text-gray-900 mb-1">Student Created!</h2>
            <p className="text-sm text-gray-500">Share these credentials with the student</p>
          </div>

          {/* The account was created either way — the photo is the only casualty. */}
          {photoWarning && (
            <div className="bg-amber-50 border border-amber-200 text-amber-800 text-sm rounded-lg px-4 py-2.5 mb-4">
              {photoWarning}
            </div>
          )}

          {credentials && (
            <div className="bg-gray-50 rounded-lg p-4 mb-6 space-y-3">
              <div className="flex justify-between items-center">
                <span className="text-xs text-gray-500 uppercase tracking-wide">Admission Number</span>
                <span className="text-sm font-mono font-semibold text-gray-900">{credentials.admissionNumber}</span>
              </div>
              <div className="border-t border-gray-200" />
              <div className="flex justify-between items-center">
                <span className="text-xs text-gray-500 uppercase tracking-wide">Temporary Password</span>
                <span className="text-sm font-mono font-semibold text-gray-900">{credentials.tempPassword}</span>
              </div>
              <div className="border-t border-gray-200" />
              <div className="flex justify-between items-center">
                <span className="text-xs text-gray-500 uppercase tracking-wide">Email</span>
                <span className="text-sm text-gray-900">{credentials.email}</span>
              </div>
            </div>
          )}

          <div className="flex gap-3">
            <button
              onClick={handleCopyCredentials}
              className="flex-1 px-4 py-2.5 text-sm font-medium text-green-700 bg-green-50 hover:bg-green-100 rounded-lg transition-colors flex items-center justify-center gap-2 min-h-[44px]"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy Credentials
                </>
              )}
            </button>
            <button
              onClick={handleClose}
              className="flex-1 px-4 py-2.5 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg transition-colors min-h-[44px]"
            >
              Close
            </button>
          </div>

          <p className="text-xs text-gray-400 text-center mt-4">
            The student will be prompted to change their password on first login.
          </p>
        </div>
      )}
    </div>
  );
};


/**
 * One tickable list. Shared by Subjects and Activities so the two can't drift
 * apart visually; `locked` is what a core subject sets.
 */
const PickList: React.FC<{
  title: string;
  rows: Array<{
    id: string;
    name: string;
    colour: string;
    locked: boolean;
    badge?: string;
  }>;
  chosen: Set<string>;
  onToggle: (id: string) => void;
}> = ({ title, rows, chosen, onToggle }) => (
  <section className="border border-gray-200 rounded-lg">
    <header className="px-3 py-2 border-b border-gray-100 flex items-center justify-between">
      <h4 className="text-sm font-medium text-gray-900">{title}</h4>
      <span className="text-xs text-gray-400">
        {rows.filter((r) => chosen.has(r.id)).length} of {rows.length}
      </span>
    </header>
    <div className="divide-y divide-gray-100">
      {rows.map((r) => {
        const on = chosen.has(r.id);
        return (
          <button
            key={r.id}
            type="button"
            onClick={() => onToggle(r.id)}
            disabled={r.locked}
            aria-pressed={on}
            className={`w-full flex items-center gap-3 px-3 py-2.5 text-left transition-colors ${
              r.locked ? 'cursor-not-allowed' : 'hover:bg-gray-50'
            }`}
          >
            <span
              className={`w-5 h-5 rounded border flex items-center justify-center shrink-0 ${
                on
                  ? 'bg-green-600 border-green-600 text-white'
                  : 'border-gray-300'
              } ${r.locked ? 'opacity-60' : ''}`}
            >
              {on && (
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                </svg>
              )}
            </span>
            <span
              className="w-3 h-3 rounded-full shrink-0"
              style={{ backgroundColor: r.colour }}
              aria-hidden="true"
            />
            <span className="text-sm text-gray-900 flex-1 min-w-0 truncate">
              {r.name}
            </span>
            {r.badge && (
              <span
                className={`text-xs px-2 py-0.5 rounded-full capitalize ${
                  r.locked ? 'bg-gray-900 text-white' : 'bg-gray-100 text-gray-600'
                }`}
              >
                {r.badge}
              </span>
            )}
          </button>
        );
      })}
    </div>
  </section>
);

export default AddStudentModal;
